// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlanoDePagamento.Data;

#nullable disable

namespace PlanoDePagamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226050140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlanoDePagamento.Models.CentroDeCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CentrosDeCusto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5206),
                            CriadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5203),
                            Descricao = "Taxa de matrícula",
                            Nome = "MATRÍCULA"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5208),
                            CriadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5208),
                            Descricao = "Mensalidade escolar/acadêmica",
                            Nome = "MENSALIDADE"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            AtualizadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5210),
                            CriadoEm = new DateTime(2026, 2, 26, 5, 1, 39, 974, DateTimeKind.Utc).AddTicks(5209),
                            Descricao = "Material didático/escolar",
                            Nome = "MATERIAL"
                        });
                });

            modelBuilder.Entity("PlanoDePagamento.Models.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodigoPagamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("integer");

                    b.Property<int>("PlanoDePagamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPagamento")
                        .IsUnique();

                    b.HasIndex("PlanoDePagamentoId");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CobrancaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CobrancaId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.PlanoDePagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CentroDeCustoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResponsavelFinanceiroId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeCustoId");

                    b.HasIndex("ResponsavelFinanceiroId");

                    b.ToTable("PlanosDePagamento");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.ResponsavelFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identificador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Identificador")
                        .IsUnique();

                    b.ToTable("ResponsaveisFinanceiros");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.Cobranca", b =>
                {
                    b.HasOne("PlanoDePagamento.Models.PlanoDePagamento", "PlanoDePagamento")
                        .WithMany("Cobrancas")
                        .HasForeignKey("PlanoDePagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoDePagamento");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.Pagamento", b =>
                {
                    b.HasOne("PlanoDePagamento.Models.Cobranca", "Cobranca")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CobrancaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cobranca");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.PlanoDePagamento", b =>
                {
                    b.HasOne("PlanoDePagamento.Models.CentroDeCusto", "CentroDeCusto")
                        .WithMany("PlanosDePagamento")
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlanoDePagamento.Models.ResponsavelFinanceiro", "ResponsavelFinanceiro")
                        .WithMany("PlanosDePagamento")
                        .HasForeignKey("ResponsavelFinanceiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroDeCusto");

                    b.Navigation("ResponsavelFinanceiro");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.CentroDeCusto", b =>
                {
                    b.Navigation("PlanosDePagamento");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.Cobranca", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.PlanoDePagamento", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("PlanoDePagamento.Models.ResponsavelFinanceiro", b =>
                {
                    b.Navigation("PlanosDePagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
